#+TITLE: Readme
#+AUTHOR: Haider Mirza

* Table of contents :toc:
- [[#who-am-i][Who am I?]]
- [[#about-this-repository][About this repository]]
  - [[#blend-files][Blend-files]]
  - [[#the-renders][The Renders]]
  - [[#helpful-documents][Helpful Documents]]

* Who am I?
#+begin_src
  _   _ __  ___
 | | | |  \/  |
 | |_| | |\/| | My Github: https://github.com/Ha1derMirza
 |  _  | |  | | My Matrix: @haider.mirza:matrix.org
 |_| |_|_|  |_|
#+end_src
My Name is Haider Mirza and I am a 3D artist and Programmer.
All my projects are hosted on github and are free and open-source.
Most of my projects are licensed under GPL V3.

* About this repository
This repository contains some of my Blender projects I have been working on or are practice/tests.
** Blend-files
The folder ".Blend-files" contains of the actual Blender Files I used.
** The Renders
There is a Test and official Renders as some of these renders are just tests and some are some official ones I am actually proud about creating.
** Helpful Documents
In this directory are some useful documents related to Blender.
